# Generated by Django 3.0 on 2019-12-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='productos',
            field=models.ManyToManyField(blank=True, to='productos.Producto'),
        ),
    ]
