# Generated by Django 3.0 on 2019-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen'),
        ('carritos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='carritos.CarritoProductos', to='productos.Producto'),
        ),
    ]
