# Generated by Django 3.0 on 2019-12-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='carrito_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
