# Generated by Django 3.0 on 2019-12-17 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordenes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carritos', '0002_carrito_productos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[(ordenes.models.OrdenEstado['CREADO'], 'CREADA'), (ordenes.models.OrdenEstado['PAGADO'], 'PAGADA'), (ordenes.models.OrdenEstado['COMPLETADA'], 'COMPLETADA'), (ordenes.models.OrdenEstado['CANCELADA'], 'CANCELADA')], default=ordenes.models.OrdenEstado['CREADO'], max_length=50)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carritos.Carrito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
