# Generated by Django 3.0 on 2019-12-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigos_promocionales', '0001_initial'),
        ('ordenes', '0003_orden_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='codigo_promocion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codigos_promocionales.CodigoPromocional'),
        ),
    ]
