# Generated by Django 3.0 on 2019-12-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0001_initial'),
        ('ordenes', '0004_orden_codigo_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_profiles.BillingProfiles'),
        ),
    ]
